version: 2

models:
  - name: foo
    description: One record per customer
    columns:
      - name: id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: name
        description: random name