version: 2

sources:
  - name: jaffle_shop
    database: dev
    schema: jaffle_shop_raw
    tables:
      - name: raw_items
        columns:
          - name: id
            description: primary key
          - name: order_id
          - name: sku
            description: describes the sku