version: 2

sources:
  - name: baz
    database: sources_only
    schema: public
    tables:
      - name: source_baz
        description: baz
        columns:
          - name: id
            description: primary key